default:
  mode: "normal"
  timeout: 30
  threads: 10
  delay_range: [0.5, 1.5]
  output_formats: ["json", "html"]
  output_dir: "./results"
  subfinder_config:
    timeout: 300
    threads: 10
  nuclei_config:
    timeout: 600
    severity: ["medium", "high", "critical"]
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
  api_keys:
    virustotal: "${VIRUSTOTAL_API_KEY}"
    shodan: "${SHODAN_API_KEY}"
    censys: "${CENSYS_API_KEY}"
